# Практическая работа №2: Обработка выборочных данных. Нахождение точечных оценок параметров распределения.

Выполнили студенты гр. 2381 Долотов Никита и Зазуля Илья. Вариант №18

## Цель работы

Получение практических навыков нахождения точечных статистических оценок параметров распределения.

## Основные теоретические положения

Условными называют варианты, определяемые равенством
$$u_j = \frac{x_j - C}{h}$$
где C - ложный ноль (новое начало отсчета), значение которого выбирается равным значению варианты интервального ряда, являющейся средней или близкой к средней по значению в этом ряду, h - ширина интервала.

Начальным эмпирическим моментом k-го порядка называется среднее значение k-х степеней элементов вариационного или интервального ряда:
$$\bar M_k = \frac{1}{N} \sum n_j x_j^k$$

В частности выборочное среднее:
$$\bar x_{\text{в}} = \bar M_1 = \frac{1}{N} \sum n_j x_j$$

Центральным эмпирическим моментом k-го порядка называется среднее значение k-х степеней разностей $(x_j - \bar x)$ для вариационного или интервального ряда:
$$\bar m_k = \frac{1}{N} \sum n_j (x_j - \bar x_{\text{в}})^k$$

В частности, дисперсия:
$$D_{\text{в}} = \bar m_2 = \frac{1}{N} \sum n_j (x_j - \bar x_{\text{в}})^2$$

Условные моменты k-го порядка:
$$\bar M_k^*=\frac{1}{N} \sum n_j \left(\frac{x_j - C}{h} \right)^k = \frac{1}{N} \sum n_j \cdot u_j^k$$

Исправленная оценка дисперсии определяется как:
$$s^2 = \frac{N}{N-1} D_{\text{в}}$$

Выборочное СКО определятеся как:
$$\sigma_{\text{в}} = \sqrt{D_{\text{в}}}$$

Исправленное СКО определяется как:
$$s = \sqrt{s^2}$$

Статистические оценки асимиетрии и эксцесса вычисляются по формулам:
$$\bar A_s = \frac{\bar m_3}{s^3}; \bar E = \frac{\bar m_4}{s^4} - 3$$

Модой $M_o^{*}$ вариационного ряда называется варианта, которой соответствует наибольшая частота. Для интервального ряда мода находится внутри интервала $(x_{i-1}, x_i)$, которому соответствует наибольшая частота и ее приближенное значение может быть вычислено по формуле:
$$M_o^{*} = x_{i-1} + h \frac{\tilde{m}_i - \tilde{m}_{i-1}}{(\tilde{m}_i - \tilde{m}_{i-1}) + (\tilde{m}_i - \tilde{m}_{i+1})}$$

Медианой $M_e^{*}$ называется варианта, соответствующая середине ранжированного ряда. Для интервального ряда выборочное значение медианы может быть вычислено по формуле:
$$M_e^{*} = x_{i-1} + \frac{h}{\tilde{m}_i}\left(0.5 - \sum_{j=1}^{i-1} \tilde{m}_j\right)$$

Выборочный коэффициент вариации $V^{*}$ характеризует разброс значений вариант относительно выборочного среднего:
$$V^{*} = \frac{\sigma_{\text{в}}}{|\bar x_{\text{в}}|} \cdot 100 \%$$

## Постановка задачи

Для заданных выборочных данных вычислить с использованием метода моментов и условных вариант точечные статистические оценки математического ожидания, дисперсии, среднеквадратичного отклонения, асимметрии, эксцесса, моды, медианы и коэффициента вариации исследуемой случайной величины. Полученные результаты содержательно проинтерпретировать.

## Выполнение работы

In [9]:
import pandas as pd
import numpy as np
from IPython.display import display, Math

### Задание 1

In [15]:
C = 466.06
h = 34.88
N = 104

x_mids = np.array([361.44, 396.31, 431.19, 466.06, 500.94, 535.81, 570.69, 605.56], dtype=float)
n = np.array([3, 17, 29, 22, 20, 8, 3, 2], dtype=float)
u = np.array([(x_mid - C) / h for x_mid in x_mids], dtype=float)


rows = []

for i in range(len(u)):
    rows.append({
        "x_i": x_mids[i],
        "n_i": n[i],
        "u_i": round(u[i]),
        "n_i*u_i": n[i] * round(u[i]),
        "n_i*u_i^2": n[i] * round(u[i])**2,
        "n_i*u_i^3": n[i] * round(u[i])**3,
        "n_i*u_i^4": n[i] * round(u[i])**4,
        "n_i*(u_i+1)^4": n[i] * (round(u[i]) + 1)**4,
    })

df = pd.DataFrame(rows)
df.index = range(1, len(df) + 1)
df.loc["Σ"] = {
    "x_i": "-",
    "n_i": df["n_i"].sum(),
    "u_i": "-",
    "n_i*u_i": df["n_i*u_i"].sum(),
    "n_i*u_i^2": df["n_i*u_i^2"].sum(),
    "n_i*u_i^3": df["n_i*u_i^3"].sum(),
    "n_i*u_i^4": df["n_i*u_i^4"].sum(),
    "n_i*(u_i+1)^4": df["n_i*(u_i+1)^4"].sum(),
}

df

      x_i    n_i u_i  n_i*u_i  n_i*u_i^2  n_i*u_i^3  n_i*u_i^4  n_i*(u_i+1)^4
1  361.44    3.0  -3     -9.0       27.0      -81.0      243.0           48.0
2  396.31   17.0  -2    -34.0       68.0     -136.0      272.0           17.0
3  431.19   29.0  -1    -29.0       29.0      -29.0       29.0            0.0
4  466.06   22.0   0      0.0        0.0        0.0        0.0           22.0
5  500.94   20.0   1     20.0       20.0       20.0       20.0          320.0
6  535.81    8.0   2     16.0       32.0       64.0      128.0          648.0
7  570.69    3.0   3      9.0       27.0       81.0      243.0          768.0
8  605.56    2.0   4      8.0       32.0      128.0      512.0         1250.0
Σ       -  104.0   -    -19.0      235.0       47.0     1447.0         3073.0

Проведем контроль вычислений по формуле: \
$N + 4\sum n_iu_i + 6\sum n_iu_i^2 + 4\sum n_iu_i^3 + \sum n_iu_i^4 = \sum n_i(u_i + 1)^4$

In [17]:
sum_n = df.loc["Σ", 'n_i']
sum_nu = df.loc["Σ", 'n_i*u_i']
sum_nu2 = df.loc["Σ", 'n_i*u_i^2']
sum_nu3 = df.loc["Σ", 'n_i*u_i^3']
sum_nu4 = df.loc["Σ", 'n_i*u_i^4']
sum_nu_1_4 = df.loc["Σ", 'n_i*(u_i+1)^4']

final = sum_n + 4*sum_nu + 6*sum_nu2 + 4*sum_nu3 + sum_nu4
print(f"{sum_n} + 4*{sum_nu} + 6*{sum_nu2} + 4*{sum_nu3} + {sum_nu4} = {final}")

104.0 + 4*-19.0 + 6*235.0 + 4*47.0 + 1447.0 = 3073.0

### Задание 2

In [11]:
M = [1 / N * (n * (u ** i)).sum() for i in range(1, 5)]

m = [
    0,
    ( M[1] - M[0]**2 ) * h**2,
    ( M[2] - 3*M[1]*M[0] + 2*(M[0]**3) ) * h**3,
    ( M[3] - 4*M[2]*M[0] + 6*M[1]*(M[0]**2) - 3*(M[0]**4) ) * h**4,
]

rows = []

for i in range(len(M)):
  rows.append({
      "M": M[i],
      "m": m[i],
  })

df = pd.DataFrame(rows)
df.index = range(1, len(df) + 1)
df

           M             m
1  -0.182590  0.000000e+00
2   2.258943  2.707701e+03
3   0.452155  7.117975e+04
4  13.905436  2.173484e+07

### Задание 3

Выведем формулы через условные варианты:

$x_j = u_j \cdot h + C$ \
$\bar x_{\text{в}} = \frac{1}{N} \sum n_j x_j = \frac{1}{N} \sum n_j (u_j \cdot h + C) = C + \frac{h}{N} \sum n_j u_j$

$D_{\text{в}} = \frac{1}{N} \sum n_j (x_j - \bar x_{\text{в}})^2 = \frac{1}{N} \sum n_j \left( h (u_j - \bar u)  \right)^2 = h^2 \left( \frac{1}{N} \sum n_j (u_j - \bar u)^2 \right)$

In [21]:
xv_std = 1 / N * np.sum(n * x_mids)
u_sum = 1 / N * np.sum(n * u)
xv_cnd = C + h * u_sum

D_std = np.sum(n * (x_mids - xv_std)**2) / N
D_cnd = h**2 / N * np.sum(n * (u - u_sum)**2)

display(Math(rf"\bar{{x}}_в = {xv_std}"))
display(Math(rf"\bar{{x}}_в = {xv_cnd}"))
display(Math(rf"D_в = {D_std}"))
display(Math(rf"D_в = {D_cnd}"))

sigma_v = np.sqrt(D_std)
display(Math(rf"\sigma_в = {sigma_v}"))

### Задание 4

In [22]:
s_2 = N / (N - 1) * D_std
s = np.sqrt(s_2)

display(Math(rf"s^2 = {s_2}"))
display(Math(rf"s = {s}"))

Исправленная выборочная дисперсия получилась немного больше смещённой, потому что при расчёте смещённой дисперсии деление выполняется на $N$, из-за чего оценка разброса слегка занижается, тогда как деление на $N-1$ вводит поправку и компенсирует это занижение, делая оценку ближе к разбросу в генеральной совокупности; аналогично, смещённое стандартное отклонение чуть меньше исправленного, но разница между ними совсем мала, поскольку СКО получается извлечением корня из дисперсии и корень дополнительно сглаживает различие.

### Задание 5

In [24]:
A_s = m[2] / s**3
E = m[3] / s**4 - 3

display(Math(rf"\bar A_s = {A_s}"))
display(Math(rf"\bar E = {E}"))

По полученным оценкам $\bar A_s \approx 0.498$ распределение имеет умеренную правостороннюю асимметрию: заметна тенденция к более длинному “хвосту” справа, то есть относительно среднего чаще встречаются большие значения, чем в симметричном случае. Оценка эксцесса $\bar E \approx -0.092$ слегка отрицательная, значит распределение немного более плосковершинное, чем нормальное: выраженного острого пика нет, а значения чуть более “размазаны” вокруг среднего. В целом отклонения от нормальной формы небольшие, но правый хвост выражен сильнее, чем у полностью симметричного распределения.

### Задание 6

In [29]:
# Наибольшая частота у 3 интервала
i = 2
left = 413.75
right = 448.62
m_i = 0.2788
m_i_plus = 0.2115
m_i_minus = 0.1635

m = [0.0288, 0.1635, 0.2788, 0.2115, 0.1923, 0.0769, 0.0288, 0.0192, 0.9998]

moda = left + h * (m[i] - m[i-1]) / ( (m[i] - m[i-1]) + (m[i] - m[i+1]) )
median = left + h / m[i] * (0.5 - np.sum([m[j] for j in range(i)]))
V = sigma_v / np.abs(xv_std) * 100

display(Math(rf"M^*_o = {moda}"))
display(Math(rf"M^*_e = {median}"))
display(Math(rf"V^* = {V}"))

По результатам расчётов для интервального ряда получены $M_o^{*} \approx 435.77$, $M_e^{*} \approx 417.37$ и $V^{*} \approx 11.32 \%$. Значение моды больше медианы (435.77>417.37), значит наиболее часто встречающиеся значения расположены правее центра распределения, а сама форма распределения смещена в сторону больших значений (наблюдается асимметрия с уклоном вправо). Коэффициент вариации показывает относительную изменчивость признака; при значении $> 5\%$, а конкретно $V^{*} \approx 11.32 \%$ имеем небольшой разброс элементов выборки. Совокупность можно считать однородной, а вариацию признака — умеренной.

## Выводы

В ходе выполнения практической работы по заданным выборочным данным были получены точечные статистические оценки основных параметров распределения.
Для упрощения вычислений введены условные варианты $u$, по которым рассчитаны условные эмпирические моменты, а затем с использованием связей между условными и центральными моментами найдены центральные эмпирические моменты.
Корректность вычислений подтверждена совпадением результатов, полученных двумя способами: выборочное среднее составило $\bar x_{\text{в}} \approx 459.69$, а выборочная дисперсия $D_{\text{в}} \approx 2707.70$. На их основе определено выборочное СКО $\sigma_{\text{в}} \approx 52.04$, а также рассчитаны исправленные оценки дисперсии и СКО: $s^2 \approx 2733.99$ и $s \approx 52.29$; при этом исправленная дисперсия ожидаемо оказалась немного выше смещённой из-за поправки $\frac{N}{N-1}$. \
По центральным моментам третьего и четвёртого порядков найдены коэффициенты асимметрии и эксцесса: $\bar A_s \approx 0.498$ и $\bar E \approx -0.092$, что указывает на умеренную правостороннюю асимметрию и слегка плосковершинную форму распределения по сравнению с нормальным. \
Дополнительно вычислены мода и медиана интервального ряда их сопоставление согласуется с выводом о смещении распределения в сторону больших значений. Рассчитанный коэффициент вариации
$V^* \approx 11.32 \%$ показал, что относительный разброс небольшой, совокупность можно считать однородной, а вариацию признака — умеренной.